### ISSUE TITLE
CONSENT-correct: line 202: 34177 Illegal instruction

### ISSUE THREAD

**Issue by kathrine-mcaulay** [morispi/LoRSCo#23]
I'm getting the following error during correction:

CONSENT-correct: line 202: 34177 Illegal instruction     $LRSCf/bin/CONSENT-correction -a $tmpdir/"$alignments" -s "$minSupport" -S "$maxSupport" -l "$windowSize" -k "$merSize" -c "$commonKMers" -A "$minAnchors" -f "$solid" -m "$windowOverlap" -j "$nproc" -r "$reads" -M "$maxMSA" -p "$LRSCf" >> "$out"

It gets as far as generating the corrected reads fast file, but this is empty.

I'm running this on RHEL7

**Comment by morispi** [comment]
Hello,

I'm afraid I cannot tell much only with this error. I never encountered it throughout all the experiments I performed.
Is your data public? If so, could you share it so I can try to reproduce the issue?

Best,
Pierre

**Comment by kathrine-mcaulay** [comment]
Thanks Pierre,

My data is not public, but I could send you a smaller subset of it (600k, or I could make a smaller one still) if that's something you'd be willing to look at?

Incidentally, the subsetted data causes a segmentation fault at the same line, rather than the same illegal instruction error. I suspect that the two are related and it may have something to do with my system, though I do have all of the stated dependencies.

Alternatively, do you have a set of ONT reads that you know work on your system? I could try these on mine. The PacBio example reads worked fine.

I am using ONT generated fastq, and have replaced all of the spaces in the header to underscores after reading [issue 4](https://github.com/morispi/CONSENT/issues/4)

**Comment by morispi** [comment]
I could work with a small subset that you know is causing the issue, yes. Of course, I would not be using it for any other purpose than testing and resolving the issue.

I believe the two can be linked, indeed, but it's usually hard to spot where / why a segmentation fault occurs when all goes well with my data.

I know this set of ONT reads works with me: https://www.genoscope.cns.fr/externe/nas/datasets/MinION/ecoli/ It's an old dataset and is has a relatively high error rate, but it sould work for the sake of testing.

Waiting for your data if you wish to share it.

Best,
Pierre

**Comment by kathrine-mcaulay** [comment]
Pierre helped me with this offline. It looks like I was running into memory allocation issues running in a head node in our computing cluster (even with a smaller 500MB subset of the reads). I was successfully able to complete the correction process by submitting as a multi-threaded job to our grid nodes (for a 16GB fastq file I requested h_vmem 4G and 32 threads, but the max v_mem was only 15GB, so I will pare this back in the future).

I still don't entirely know what the problem was, but this was an acceptable solution.

Thank you for your help Pierre.
