### ISSUE TITLE
problem with CONSENT

### ISSUE THREAD

**Issue by lfaino** [morispi/LoRSCo#6]
Dear Developer, I get this error. Can you please help me?

 
lfaino@LabReverberiPT /nanopore/data/MLST_3_samples/demultiplex $ ~/bin/CONSENT/CONSENT-correct --in barcode10_flipflop_barcode.fastq --minSupport 100  --out barcode10_flipflop_barcode.fasta --type ONT
[Fri Feb 15 20:50:02 CET 2019] Self-aligning the long reads (minimap2)
error: Found argument '-f' which wasn't expected, or isn't valid in this context

USAGE:
    fpa [FLAGS] [OPTIONS] [ARGS]

For more information try --help
[M::mm_idx_gen::0.109*1.01] collected minimizers
[M::mm_idx_gen::0.137*1.87] sorted minimizers
[M::main::0.137*1.87] loaded/built the index for 9600 target sequence(s)
[M::mm_mapopt_update::0.145*1.82] mid_occ = 448
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 9600
[M::mm_idx_stat::0.151*1.79] distinct minimizers: 592279 (89.77% are singletons); average occurrences: 2.130; average spacing: 3.054>

Cheers
Luigi

**Comment by morispi** [comment]
Hey!

Which fpa version are you using?
It should be okay from release v0.4 (Nidoqueen) on.
How did you compile it?

Cheers
Pierre

**Comment by morispi** [comment]
Closing the issue as fpa is no longer used.
